<?php

/**
 * Baserubro
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property Doctrine_Collection $plan
 * 
 * @method string              getNombre() Returns the current record's "nombre" value
 * @method Doctrine_Collection getPlan()   Returns the current record's "plan" collection
 * @method rubro               setNombre() Sets the current record's "nombre" value
 * @method rubro               setPlan()   Sets the current record's "plan" collection
 * 
 * @package    universal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baserubro extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rubro');
        $this->hasColumn('nombre', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('plan', array(
             'local' => 'id',
             'foreign' => 'rubro_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}