<?php

/**
 * Baseproductor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $localidad_id
 * @property string $codigo
 * @property string $zona
 * @property string $apellido
 * @property string $nombre
 * @property string $domicilio
 * @property string $tel
 * @property string $celular
 * @property integer $usuario_id
 * @property localidad $localidad
 * @property Doctrine_Collection $suscripcion
 * 
 * @method integer             getLocalidadId()  Returns the current record's "localidad_id" value
 * @method string              getCodigo()       Returns the current record's "codigo" value
 * @method string              getZona()         Returns the current record's "zona" value
 * @method string              getApellido()     Returns the current record's "apellido" value
 * @method string              getNombre()       Returns the current record's "nombre" value
 * @method string              getDomicilio()    Returns the current record's "domicilio" value
 * @method string              getTel()          Returns the current record's "tel" value
 * @method string              getCelular()      Returns the current record's "celular" value
 * @method integer             getUsuarioId()    Returns the current record's "usuario_id" value
 * @method localidad           getLocalidad()    Returns the current record's "localidad" value
 * @method Doctrine_Collection getSuscripcion()  Returns the current record's "suscripcion" collection
 * @method productor           setLocalidadId()  Sets the current record's "localidad_id" value
 * @method productor           setCodigo()       Sets the current record's "codigo" value
 * @method productor           setZona()         Sets the current record's "zona" value
 * @method productor           setApellido()     Sets the current record's "apellido" value
 * @method productor           setNombre()       Sets the current record's "nombre" value
 * @method productor           setDomicilio()    Sets the current record's "domicilio" value
 * @method productor           setTel()          Sets the current record's "tel" value
 * @method productor           setCelular()      Sets the current record's "celular" value
 * @method productor           setUsuarioId()    Sets the current record's "usuario_id" value
 * @method productor           setLocalidad()    Sets the current record's "localidad" value
 * @method productor           setSuscripcion()  Sets the current record's "suscripcion" collection
 * 
 * @package    universal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseproductor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('productor');
        $this->hasColumn('localidad_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('codigo', 'string', 10, array(
             'type' => 'string',
             'unique' => true,
             'length' => 10,
             ));
        $this->hasColumn('zona', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('apellido', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('nombre', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('domicilio', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('tel', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('celular', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('usuario_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('localidad', array(
             'local' => 'localidad_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('suscripcion', array(
             'local' => 'id',
             'foreign' => 'productor_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}