<?php

/**
 * Basefac_estado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property Doctrine_Collection $facturas
 * 
 * @method string              getNombre()   Returns the current record's "nombre" value
 * @method Doctrine_Collection getFacturas() Returns the current record's "facturas" collection
 * @method fac_estado          setNombre()   Sets the current record's "nombre" value
 * @method fac_estado          setFacturas() Sets the current record's "facturas" collection
 * 
 * @package    universal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basefac_estado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fac_estado');
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('facturas', array(
             'local' => 'id',
             'foreign' => 'estado_id'));
    }
}