<?php

/**
 * Basecuotas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $suscripcion_id
 * @property decimal $importe
 * @property date $femision
 * @property date $fvencimiento
 * @property date $fpago
 * @property suscripcion $suscripcion
 * 
 * @method integer     getSuscripcionId()  Returns the current record's "suscripcion_id" value
 * @method decimal     getImporte()        Returns the current record's "importe" value
 * @method date        getFemision()       Returns the current record's "femision" value
 * @method date        getFvencimiento()   Returns the current record's "fvencimiento" value
 * @method date        getFpago()          Returns the current record's "fpago" value
 * @method suscripcion getSuscripcion()    Returns the current record's "suscripcion" value
 * @method cuotas      setSuscripcionId()  Sets the current record's "suscripcion_id" value
 * @method cuotas      setImporte()        Sets the current record's "importe" value
 * @method cuotas      setFemision()       Sets the current record's "femision" value
 * @method cuotas      setFvencimiento()   Sets the current record's "fvencimiento" value
 * @method cuotas      setFpago()          Sets the current record's "fpago" value
 * @method cuotas      setSuscripcion()    Sets the current record's "suscripcion" value
 * 
 * @package    universal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecuotas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cuotas');
        $this->hasColumn('suscripcion_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('importe', 'decimal', 10, array(
             'type' => 'decimal',
             'scale' => 2,
             'default' => 0,
             'length' => 10,
             ));
        $this->hasColumn('femision', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('fvencimiento', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('fpago', 'date', null, array(
             'type' => 'date',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('suscripcion', array(
             'local' => 'suscripcion_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}