<?php

/**
 * Baselocalidad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $provincia_id
 * @property string $nombre
 * @property string $cp
 * @property provincia $provincia
 * @property Doctrine_Collection $suscriptor
 * @property Doctrine_Collection $productor
 * 
 * @method integer             getProvinciaId()  Returns the current record's "provincia_id" value
 * @method string              getNombre()       Returns the current record's "nombre" value
 * @method string              getCp()           Returns the current record's "cp" value
 * @method provincia           getProvincia()    Returns the current record's "provincia" value
 * @method Doctrine_Collection getSuscriptor()   Returns the current record's "suscriptor" collection
 * @method Doctrine_Collection getProductor()    Returns the current record's "productor" collection
 * @method localidad           setProvinciaId()  Sets the current record's "provincia_id" value
 * @method localidad           setNombre()       Sets the current record's "nombre" value
 * @method localidad           setCp()           Sets the current record's "cp" value
 * @method localidad           setProvincia()    Sets the current record's "provincia" value
 * @method localidad           setSuscriptor()   Sets the current record's "suscriptor" collection
 * @method localidad           setProductor()    Sets the current record's "productor" collection
 * 
 * @package    universal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baselocalidad extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('localidad');
        $this->hasColumn('provincia_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('nombre', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('cp', 'string', 4, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('provincia', array(
             'local' => 'provincia_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('suscriptor', array(
             'local' => 'id',
             'foreign' => 'localidad_id'));

        $this->hasMany('productor', array(
             'local' => 'id',
             'foreign' => 'localidad_id'));
    }
}