<?php

/**
 * Baseproveedor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $razon_social
 * @property string $nro_cuit
 * @property integer $iva_id
 * @property string $iibb
 * @property string $domicilio
 * @property date $inicio_actividad
 * @property integer $usuario_id
 * @property cond_iva $cond_iva
 * @property Doctrine_Collection $proveAlias
 * 
 * @method string              getRazonSocial()      Returns the current record's "razon_social" value
 * @method string              getNroCuit()          Returns the current record's "nro_cuit" value
 * @method integer             getIvaId()            Returns the current record's "iva_id" value
 * @method string              getIibb()             Returns the current record's "iibb" value
 * @method string              getDomicilio()        Returns the current record's "domicilio" value
 * @method date                getInicioActividad()  Returns the current record's "inicio_actividad" value
 * @method integer             getUsuarioId()        Returns the current record's "usuario_id" value
 * @method cond_iva            getCondIva()          Returns the current record's "cond_iva" value
 * @method Doctrine_Collection getProveAlias()       Returns the current record's "proveAlias" collection
 * @method proveedor           setRazonSocial()      Sets the current record's "razon_social" value
 * @method proveedor           setNroCuit()          Sets the current record's "nro_cuit" value
 * @method proveedor           setIvaId()            Sets the current record's "iva_id" value
 * @method proveedor           setIibb()             Sets the current record's "iibb" value
 * @method proveedor           setDomicilio()        Sets the current record's "domicilio" value
 * @method proveedor           setInicioActividad()  Sets the current record's "inicio_actividad" value
 * @method proveedor           setUsuarioId()        Sets the current record's "usuario_id" value
 * @method proveedor           setCondIva()          Sets the current record's "cond_iva" value
 * @method proveedor           setProveAlias()       Sets the current record's "proveAlias" collection
 * 
 * @package    universal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseproveedor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('proveedor');
        $this->hasColumn('razon_social', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('nro_cuit', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('iva_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('iibb', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('domicilio', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('inicio_actividad', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('usuario_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('cond_iva', array(
             'local' => 'iva_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('facturas as proveAlias', array(
             'local' => 'id',
             'foreign' => 'prov_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}