<?php

/**
 * Baseprovincia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property Doctrine_Collection $provAlias
 * 
 * @method string              getNombre()    Returns the current record's "nombre" value
 * @method Doctrine_Collection getProvAlias() Returns the current record's "provAlias" collection
 * @method provincia           setNombre()    Sets the current record's "nombre" value
 * @method provincia           setProvAlias() Sets the current record's "provAlias" collection
 * 
 * @package    universal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseprovincia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('provincia');
        $this->hasColumn('nombre', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('localidad as provAlias', array(
             'local' => 'id',
             'foreign' => 'provincia_id'));
    }
}