<?php

/**
 * Basecuota
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $suscripcion_id
 * @property integer $nro_cuota
 * @property decimal $importe
 * @property date $femision
 * @property date $fvencimiento
 * @property date $fpago
 * @property boolean $impresa
 * @property suscripcion $suscripcion
 * 
 * @method integer     getSuscripcionId()  Returns the current record's "suscripcion_id" value
 * @method integer     getNroCuota()       Returns the current record's "nro_cuota" value
 * @method decimal     getImporte()        Returns the current record's "importe" value
 * @method date        getFemision()       Returns the current record's "femision" value
 * @method date        getFvencimiento()   Returns the current record's "fvencimiento" value
 * @method date        getFpago()          Returns the current record's "fpago" value
 * @method boolean     getImpresa()        Returns the current record's "impresa" value
 * @method suscripcion getSuscripcion()    Returns the current record's "suscripcion" value
 * @method cuota       setSuscripcionId()  Sets the current record's "suscripcion_id" value
 * @method cuota       setNroCuota()       Sets the current record's "nro_cuota" value
 * @method cuota       setImporte()        Sets the current record's "importe" value
 * @method cuota       setFemision()       Sets the current record's "femision" value
 * @method cuota       setFvencimiento()   Sets the current record's "fvencimiento" value
 * @method cuota       setFpago()          Sets the current record's "fpago" value
 * @method cuota       setImpresa()        Sets the current record's "impresa" value
 * @method cuota       setSuscripcion()    Sets the current record's "suscripcion" value
 * 
 * @package    universal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecuota extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cuota');
        $this->hasColumn('suscripcion_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('nro_cuota', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('importe', 'decimal', 10, array(
             'type' => 'decimal',
             'scale' => 2,
             'default' => 0,
             'length' => 10,
             ));
        $this->hasColumn('femision', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('fvencimiento', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('fpago', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('impresa', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('suscripcion', array(
             'local' => 'suscripcion_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}