<?php

/**
 * condivaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class condivaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object condivaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('condiva');
    }
}