<?php

/**
 * cond_ivaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class cond_ivaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object cond_ivaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('cond_iva');
    }
}