<?php

/**
 * consultaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class consultaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object consultaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('consulta');
    }
}