<?php

/**
 * fac_tipoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class fac_tipoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object fac_tipoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('fac_tipo');
    }
}