<?php

/**
 * fac_estadoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class fac_estadoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object fac_estadoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('fac_estado');
    }
}