<?php

/**
 * informectbTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class informectbTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object informectbTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('informectb');
    }
}