<?php

/**
 * planTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class planTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object planTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('plan');
    }

//--- autocompletado
public function retrieveForSelect($q, $limit)
  {

$qq = Doctrine_Query::create()
//       ->select("id, concat(codigo,' ',descripcion,' $',CONVERT(valor_cuota,CHAR),' $',CONVERT(valor_nominal,CHAR)) as todo" )
       ->select("id, descripcion as todo" )
       ->from("plan")
       ->where("descripcion LIKE ?", "%$q%")
//       ->where('codigo =?', $q)
//       ->orWhere('descripcion LIKE ?', "%$q%")
       ->orderBy('descripcion')
       ->limit(100);
 
    return $qq->execute()->toKeyValueArray('id','todo');
}

//------------ búsqueda desde el plan/index
public function getResultado($buscar,$rubro){
  if ($rubro>0) {
$respuesta = Doctrine_Query::create()
       ->select("id,rubro_id,descripcion,valor_cuota")
       ->from("plan")
       ->where('descripcion LIKE ?', "%$buscar%")
       ->andWhere('rubro_id =?', $rubro)
       ->orderBy('descripcion')->execute();
return $respuesta;
   } else {
$respuesta = Doctrine_Query::create()
       ->select("id,rubro_id,descripcion,valor_cuota")
       ->from("plan")
       ->where('descripcion LIKE ?', "%$buscar%")
       ->orderBy('rubro_id')->execute();
return $respuesta;
     }
}


}
