<?php

/**
 * productorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class productorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object productorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('productor');
    }

//--- autocompletado
public function retrieveForSelect($q, $limit)
  {

$qq = Doctrine_Query::create()
       ->select("id, concat(codigo,' ',apellido,' ',nombre) as todo" )
       ->from("productor")
       ->where('codigo =?', $q)
       ->orWhere('nombre LIKE ?', "%$q%")
       ->orWhere('apellido LIKE ?', "%$q%");
       //->limit($limit);
 
    return $qq->execute()->toKeyValueArray('id','todo');
}

//------------ búsqueda de productor/index
public function getResultado($codigo){

$respuesta = Doctrine_Query::create()
       ->select("id,codigo,zona,concat(apellido,' ',nombre) as nombrefull,tel,celular ")
       ->from("productor")
       ->where('codigo =?', $codigo)
       ->orWhere('nombre LIKE ?', "%$codigo%")
       ->orWhere('apellido LIKE ?', "%$codigo%")
       ->execute();

return $respuesta;
 }

}
