<?php

/**
 * provinciaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class provinciaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object provinciaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('provincia');
    }
}