<?php

/**
 * rubroTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class rubroTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object rubroTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('rubro');
    }
}