<?php

/**
 * suscripcionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class suscripcionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object suscripcionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('suscripcion')->where('fecha_baja is null')->execute();
    }

//------------ búsqueda desde el plan/index
public function getResultado($buscar){

$respuesta = Doctrine_Query::create()
       ->select("id,codigo,plan,suscriptor_id,productor_id,fecha_alta,sorteo")
       ->from("suscripcion s")
       ->leftjoin('s.suscriptor c')
       ->where('nro LIKE ?', "%$buscar%")
       ->andwhere('fecha_baja is null')
       ->orwhere('c.apellido LIKE ?', "%$buscar%")
       ->orderBy('nro DESC')
       ->execute();
return $respuesta;
  }
//------------ ver suscripciones del suscriptor
public function verSuscriptor($id){

$respuesta = Doctrine_Query::create()
       ->select("id,codigo,plan,suscriptor_id,productor_id,fecha_alta,sorteo")
       ->from("suscripcion")
       ->where('suscriptor_id =?', "$id")
       ->execute();
return $respuesta;
  }
//------------ ver suscripciones del productor
public function verProductor($id){

$respuesta = Doctrine_Query::create()
       ->select("id,codigo,plan,suscriptor_id,productor_id,fecha_alta,sorteo")
       ->from("suscripcion")
       ->where('productor_id =?', "$id")
       ->andwhere('fecha_baja is null')->execute();
return $respuesta;
  }


//--------- contar suscripciones de un suscriptor
public static function getSuscriptor($id){

 $totalsuscripciones = Doctrine_Query::create()
       ->select("COUNT(id) as totalsuscripciones")
       ->from("suscripcion")
       ->where('suscriptor_id=?', $id)->execute();

 return $totalsuscripciones[0]['totalsuscripciones'];
}

//--------- contar suscripciones BAJAS
public static function totalBajas(){

 $totalbajas = Doctrine_Query::create()
       ->select("COUNT(id) as totalbajas")
       ->from("suscripcion")
       ->where('not fecha_baja is null')->execute();

 return $totalbajas[0]['totalbajas'];
}

//--------- contar suscripciones de un productor
public static function totalSuscripciones($id){

 $totales = Doctrine_Query::create()
       ->select("COUNT(id) as cantidad, SUM(valor_cuota) as total")
       ->from("suscripcion")
       ->where('productor_id=?', $id)
       ->andwhere('fecha_baja is null')->execute();
return $totales;
}

//--------- contar suscripciones de un Plan
public static function getPlan($id){

 $totalsuscripciones = Doctrine_Query::create()
       ->select("COUNT(id) as totalsuscripciones")
       ->from("suscripcion")
       ->where('plan=?', $id)->execute();

 return $totalsuscripciones[0]['totalsuscripciones'];
}


}
