<?php

/**
 * usuarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class usuarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object usuarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('usuario');
    }
}