<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addsuscriptor extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('suscriptor', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'localidad_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'codigo' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 5,
             ),
             'tipodni' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 3,
             ),
             'dni' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 8,
             ),
             'apellido' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 50,
             ),
             'nombre' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 50,
             ),
             'domicilio' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 100,
             ),
             'tel' => 
             array(
              'type' => 'string',
              'length' => 20,
             ),
             'conyuge' => 
             array(
              'type' => 'string',
              'length' => 100,
             ),
             'fingreso' => 
             array(
              'type' => 'date',
              'length' => 25,
             ),
             'fegreso' => 
             array(
              'type' => 'date',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('suscriptor');
    }
}