<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addprovincia extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('provincia', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'nombre' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 50,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('provincia');
    }
}