<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addsuscripcion extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('suscripcion', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'plan_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'suscriptor_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'productor_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'cuotas' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'nro' => 
             array(
              'type' => 'string',
              'length' => 6,
             ),
             'fecha' => 
             array(
              'type' => 'date',
              'length' => 25,
             ),
             'activo' => 
             array(
              'type' => 'boolean',
              'notnull' => true,
              'default' => 1,
              'length' => 25,
             ),
             'sorteo' => 
             array(
              'type' => 'string',
              'length' => 3,
             ),
             'dia_pago' => 
             array(
              'type' => 'string',
              'length' => 2,
             ),
             'obs' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('suscripcion');
    }
}