<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addcuotas extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('cuotas', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'suscripcion_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'importe' => 
             array(
              'type' => 'decimal',
              'scale' => 2,
              'default' => 0,
              'length' => 10,
             ),
             'femision' => 
             array(
              'type' => 'date',
              'length' => 25,
             ),
             'fvencimiento' => 
             array(
              'type' => 'date',
              'length' => 25,
             ),
             'fpago' => 
             array(
              'type' => 'date',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('cuotas');
    }
}