<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addplan extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('plan', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'rubro_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'codigo' => 
             array(
              'type' => 'string',
              'length' => 5,
             ),
             'descripcion' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 100,
             ),
             'valor_nominal' => 
             array(
              'type' => 'decimal',
              'scale' => 2,
              'default' => 0,
              'length' => 10,
             ),
             'valor_cuota' => 
             array(
              'type' => 'decimal',
              'scale' => 2,
              'default' => 0,
              'length' => 10,
             ),
             'cant_cuotas' => 
             array(
              'type' => 'integer',
              'default' => 0,
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('plan');
    }
}