<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/03/11 12:45:55

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=127.0.0.1;dbname=universal',
  'username' => 'universal',
  'password' => 'universal',
  'name' => 'doctrine',
)),);
